
before_script:
  - export CXX=$COMPILER
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
    sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
    fi

matrix:
  include:
    - name: "OpenJDK 8"
      language: java
      jdk: openjdk8
      os: linux
      dist: xenial
      script: ./gradlew --scan

    - name: "OpenJDK 11"
      language: java
      jdk: openjdk11
      os: linux
      dist: xenial
      script: ./gradlew --scan

    - env: COMPILER=clang++-5.0
      language: c++
      compiler: clang
      os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - clang-5.0
            - libstdc++-7-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-5.0
      script: cppbuild/cppbuild --build-archive-api

    - env: COMPILER=clang++-6.0
      language: c++
      compiler: clang
      os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - clang-6.0
            - libstdc++-7-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-6.0
      script: cppbuild/cppbuild --build-archive-api

    - env: COMPILER=clang++-7
      language: c++
      compiler: clang
      os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - clang-7
            - libstdc++-7-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-7
      script: cppbuild/cppbuild --build-archive-api

    - name: "Clang 7 debug build"
      env: COMPILER=clang++-7
      language: c++
      compiler: clang
      os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - clang-7
            - libstdc++-7-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-7
      script: cppbuild/cppbuild --debug-build --build-archive-api

    - env: COMPILER=g++-6
      language: c++
      compiler: gcc
      os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - g++-6
          sources:
            - ubuntu-toolchain-r-test
      script: cppbuild/cppbuild --build-archive-api

    - env: COMPILER=g++-7
      language: c++
      compiler: gcc
      os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - g++-7
          sources:
            - ubuntu-toolchain-r-test
      script: cppbuild/cppbuild --build-archive-api

    - env: COMPILER=g++-8
      language: c++
      compiler: gcc
      os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - g++-8
          sources:
            - ubuntu-toolchain-r-test
      script: cppbuild/cppbuild --build-archive-api

    - env: COMPILER=clang++
      language: c++
      compiler: clang
      os: osx
      script: cppbuild/cppbuild --build-archive-api

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
