name: Continuous Integration
on:
  repository_dispatch:
    types: run-commit-tests
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]
    branches:
      - master

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

jobs:
  java-build:
    name: Java ${{ matrix.java }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java: [ '8', '11', '14' ]
        os: ['ubuntu-latest', 'windows-latest']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache Gradle dependencies
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-
      - name: Cache Gradle wrappers
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Gradle
        run: ./gradlew
      - name: Copy crash logs
        id: copy_crash_logs
        if: failure()
        run: |
          echo "::set-output name=dir::build/crash_logs"

          ./gradlew copyCrashLogs
      - name: Upload crash logs
        if: always() && steps.copy_crash_logs.outputs.dir == 'build/crash_logs'
        uses: actions/upload-artifact@v1
        with:
          name: crash-logs-${{ matrix.os }}-java-${{ matrix.java }}
          path: ${{ steps.copy_crash_logs.outputs.dir }}

  cpp-gcc-build:
    name: C++ GCC ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [ '6', '7', '8', '9', '10' ]
    env:
      CC: gcc-${{ matrix.version }}
      CXX: g++-${{ matrix.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache Gradle dependencies
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-
      - name: Cache Gradle wrappers
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
      - name: Install compiler
        run: |
         sudo apt-get update

         sudo apt-get install -y g++-${{ matrix.version }} libbsd-dev uuid-dev
      - name: Build
        run: cppbuild/cppbuild --build-archive-api

  cpp-gcc-centos-build:
    name: C++ GCC ${{ matrix.version }} (CentOS)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [ '9' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache Gradle dependencies
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-
      - name: Cache Gradle wrappers
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
      - name: Build
        run: cppbuild/centos-docker-build ${{ matrix.version }}

  cpp-clang-build:
    name: C++ Clang ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [ '6.0', '7', '8', '9', '10' ]
    env:
      CC: clang-${{ matrix.version }}
      CXX: clang++-${{ matrix.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache Gradle dependencies
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-
      - name: Cache Gradle wrappers
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
      - name: Install compiler
        run: |
          sudo add-apt-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-${{ matrix.version }} main"

          sudo apt-get update

          sudo apt-get install -y clang-${{ matrix.version }} libstdc++-7-dev libbsd-dev uuid-dev
      - name: Build
        run: cppbuild/cppbuild --build-archive-api

  cpp-clang-debug-build:
    name: C++ Clang ${{ matrix.version }} debug build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [ '7' ]
    env:
      CC: clang-${{ matrix.version }}
      CXX: clang++-${{ matrix.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache Gradle dependencies
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-
      - name: Cache Gradle wrappers
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
      - name: Install compiler
        run: |
          sudo add-apt-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-${{ matrix.version }} main"

          sudo apt-get update

          sudo apt-get install -y clang-${{ matrix.version }} libstdc++-7-dev libbsd-dev uuid-dev
      - name: Build
        run: cppbuild/cppbuild --debug-build --build-archive-api

  cpp-clang-macos-build:
    name: C++ Xcode ${{ matrix.version }} (macOS)
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        version: [ '11.4' ]
    env:
      CC: clang
      CXX: clang++
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install compiler
        run: |
          sudo xcode-select -switch /Applications/Xcode_${{ matrix.version }}.app
      - name: Build
        run: cppbuild/cppbuild

  cpp-msvc-build:
    name: C++ MSVC (Windows)
    runs-on: windows-latest
    strategy:
      fail-fast: false
    env:
      CC: cl
      CXX: cl
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: cppbuild/cppbuild-vs
